Fix build for Windows
This PR fixes the package so it can be imported when used under Windows.
The `syslog` package unfortunately is not supported under Windows. Hence
we disable it if we detect it.

Fixes the following error:

```
xlog.go:66:12: undefined: syslog.New
xlog.go:66:23: undefined: syslog.LOG_DEBUG
```